language: python
python:
  - "3.9"
sudo: required
services:
  - docker
script:
  - python test.py

after-success:
  - docker build -t vonpappen/PSQL-scrapper .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vonpappen/PSQL-scrapper

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'PSQL-webscrap'
  env: 'Psqlwebscrap-env'
  bucket_name: 'psql-webscrap-bucket'
  bucket_path: 'PSQL-webscrap'
  on:
    branch: main
  acess_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY