version: '3.6'

services:

  db:
    image: postgres:13.3
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres5432
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
    volumes: 
      - ./DB/postgres-data:/var/lib/postgresql/data
    ports: 
      - 4567:5432

  sqa:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres5432
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    # volumes: 
    #   - ./cron.log:/var/log/cron.log
    #   - ./cron.log_security:/var/log/cron.log_security

            # Works
            #     python initiate_database.py
            # && python securities_table/initialize_sec_table_v2.py
            # && python earnings_release/initialize_earnings_release.py
            # && python statements_table/initialize_statements_table.py


      # FIX CRONJOBS
    command: bash -c "
            cron 
            && tail -f /var/log/cron.log"
    