version: '3.6'

services:

  db:
    image: postgres:13.3
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres5432
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
    # volumes: 
      # - ./DB/postgres-data:/var/lib/postgresql/data
    ports: 
      - 4567:5432

  sqa:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres5432
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    command: bash -c "python initiate_database.py
            && python securities_table/initialize_sec_table_v2.py
            && python statements_table/initialize_statements_table.py
            && cron 
            && tail -f /var/log/cron.log"
    