version: '3.6'

services:
  sqa:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres5678
      - POSTGRES_PORT=5432
      - POSTGRES_DB=webscrapping
      - POSTGRES_HOST=database-webscrap.ccaaerr6cq44.eu-west-3.rds.amazonaws.com
    command: bash -c "
            python initiate_database.py
            && python securities_table/initialize_sec_table_v2.py
            && python statements_table/initialize_statements_table.py
            && python earnings_release/initialize_earnings_release.py
            "