version: '3.6'

services:
  
  sqa:
    image: "vonpappen/psql-scrapper"

    environment: 
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST



    command: bash -c "
            python initiate_database.py
            && python securities_table/initialize_sec_table_v2.py
            && python statements_table/initialize_statements_table.py
            && python earnings_release/initialize_earnings_release.py
            && cron 
            && tail -f /var/log/cron.log"