version: '3.6'

services:
  
  sqa:
    image: 'vonpappen/PSQL-scrapper'

    environment: 
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_PORT=$PG_PORT
      - POSTGRES_DB=$PG_DATABASE
      - POSTGRES_HOST=$PG_HOST

    command: bash -c "
            python initiate_database.py
            && python securities_table/initialize_sec_table_v2.py
            && python statements_table/initialize_statements_table.py
            && python earnings_release/initialize_earnings_release.py
            && cron 
            && tail -f /var/log/cron.log"