"""adding tables

Revision ID: 001f710e7f01
Revises: 74443727719f
Create Date: 2021-09-14 19:19:17.917817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001f710e7f01'
down_revision = '74443727719f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
