"""Changed Securities table

Revision ID: 0c48e6cc68db
Revises: bd73aba1cef1
Create Date: 2021-09-13 22:33:32.689163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c48e6cc68db'
down_revision = 'bd73aba1cef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
