"""Changed amount to FLOAT

Revision ID: 0ed4bbf17aae
Revises: ecbf512bf44d
Create Date: 2021-09-15 12:12:05.836888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed4bbf17aae'
down_revision = 'ecbf512bf44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
