"""Changed Security Model

Revision ID: 167596db52d9
Revises: eb20970a22c5
Create Date: 2021-09-14 10:27:17.279897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167596db52d9'
down_revision = 'eb20970a22c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
