"""added constraint on securities_table

Revision ID: 16967d8ea930
Revises: 3565f716f77d
Create Date: 2021-09-17 10:57:43.068724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16967d8ea930'
down_revision = '3565f716f77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_securities_table_ticker', table_name='securities_table')
    op.create_index(op.f('ix_securities_table_ticker'), 'securities_table', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_table_ticker'), table_name='securities_table')
    op.create_index('ix_securities_table_ticker', 'securities_table', ['ticker'], unique=False)
    # ### end Alembic commands ###
