"""Changed amount to FLOAT

Revision ID: 199786735512
Revises: 978612985032
Create Date: 2021-09-15 12:00:51.591521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199786735512'
down_revision = '978612985032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
