"""Changed Security Model

Revision ID: 1a2dfe10c384
Revises: 83fcc5e4ad11
Create Date: 2021-09-14 11:10:05.278995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2dfe10c384'
down_revision = '83fcc5e4ad11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
