"""modified earnings table field

Revision ID: 266d8a640471
Revises: 27fd45fae3e9
Create Date: 2021-09-17 21:38:50.013346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266d8a640471'
down_revision = '27fd45fae3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_release', sa.Column('last_period_M', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_release', 'last_period_M')
    # ### end Alembic commands ###
