"""modified earnings table field

Revision ID: 27fd45fae3e9
Revises: 87e2ecb4f7ac
Create Date: 2021-09-17 20:25:22.404592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fd45fae3e9'
down_revision = '87e2ecb4f7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_release', sa.Column('last_period_db', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_release', 'last_period_db')
    # ### end Alembic commands ###
