"""Security Model __str__

Revision ID: 2dfae025dafb
Revises: 1a2dfe10c384
Create Date: 2021-09-14 11:28:12.562226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfae025dafb'
down_revision = '1a2dfe10c384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
