"""Changed Security Model

Revision ID: 2e45fe31a2d2
Revises: 513c53f60e17
Create Date: 2021-09-14 00:50:09.938918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e45fe31a2d2'
down_revision = '513c53f60e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
