"""Security Model __str__

Revision ID: 4553f9e7c4c8
Revises: 1d30148f956c
Create Date: 2021-09-14 18:40:41.252675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4553f9e7c4c8'
down_revision = '1d30148f956c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
