"""Changed Securities table

Revision ID: 513c53f60e17
Revises: 0c48e6cc68db
Create Date: 2021-09-13 22:34:21.578233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '513c53f60e17'
down_revision = '0c48e6cc68db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Securities', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('Securities', sa.Column('company', sa.String(), nullable=True))
    op.add_column('Securities', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('Securities', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('Securities', sa.Column('country', sa.String(), nullable=True))
    op.drop_column('Securities', 'author')
    op.drop_column('Securities', 'title')
    op.drop_column('Securities', 'published')
    op.drop_column('Securities', 'pages')
    op.drop_column('Securities', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Securities', sa.Column('price', postgresql.MONEY(), autoincrement=False, nullable=True))
    op.add_column('Securities', sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Securities', sa.Column('published', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('Securities', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Securities', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Securities', 'country')
    op.drop_column('Securities', 'industry')
    op.drop_column('Securities', 'sector')
    op.drop_column('Securities', 'company')
    op.drop_column('Securities', 'ticker')
    # ### end Alembic commands ###
