"""added Earnings-release-table

Revision ID: 5d81f0e68129
Revises: 16967d8ea930
Create Date: 2021-09-17 17:51:16.211911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d81f0e68129'
down_revision = '16967d8ea930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
