"""Security Model __str__

Revision ID: 6622044721cf
Revises: 4553f9e7c4c8
Create Date: 2021-09-14 18:42:09.964053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6622044721cf'
down_revision = '4553f9e7c4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
