"""changed MONEY to VARCHAR

Revision ID: 6a477fe74fd4
Revises: c4b1b2a4fbfc
Create Date: 2021-09-14 23:09:14.836476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a477fe74fd4'
down_revision = 'c4b1b2a4fbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
