"""adding tables

Revision ID: 74443727719f
Revises: a16492295f03
Create Date: 2021-09-14 19:19:09.033671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74443727719f'
down_revision = 'a16492295f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cash_flow_statement_annual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', postgresql.MONEY(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['Securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_cfa')
    )
    op.create_index(op.f('ix_Cash_flow_statement_annual_date'), 'Cash_flow_statement_annual', ['date'], unique=False)
    op.create_index(op.f('ix_Cash_flow_statement_annual_ticker'), 'Cash_flow_statement_annual', ['ticker'], unique=False)
    op.create_table('Cash_flow_statement_quarterly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', postgresql.MONEY(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['Securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_cfq')
    )
    op.create_index(op.f('ix_Cash_flow_statement_quarterly_date'), 'Cash_flow_statement_quarterly', ['date'], unique=False)
    op.create_index(op.f('ix_Cash_flow_statement_quarterly_ticker'), 'Cash_flow_statement_quarterly', ['ticker'], unique=False)
    op.create_index('combo_index_cfa', 'Income_statement_annual', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index('combo_index_cfq', 'Income_statement_quarterly', ['date', 'ticker', 'line_item'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('combo_index_cfq', table_name='Income_statement_quarterly')
    op.drop_index('combo_index_cfa', table_name='Income_statement_annual')
    op.drop_index(op.f('ix_Cash_flow_statement_quarterly_ticker'), table_name='Cash_flow_statement_quarterly')
    op.drop_index(op.f('ix_Cash_flow_statement_quarterly_date'), table_name='Cash_flow_statement_quarterly')
    op.drop_table('Cash_flow_statement_quarterly')
    op.drop_index(op.f('ix_Cash_flow_statement_annual_ticker'), table_name='Cash_flow_statement_annual')
    op.drop_index(op.f('ix_Cash_flow_statement_annual_date'), table_name='Cash_flow_statement_annual')
    op.drop_table('Cash_flow_statement_annual')
    # ### end Alembic commands ###
