"""Test 1

Revision ID: 7516c00a44ef
Revises: 3daa14239d67
Create Date: 2021-09-15 12:25:14.701902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7516c00a44ef'
down_revision = '3daa14239d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
