"""Changed Security Model

Revision ID: 83fcc5e4ad11
Revises: 167596db52d9
Create Date: 2021-09-14 10:39:15.852039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fcc5e4ad11'
down_revision = '167596db52d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
