"""added Earnings-release-table

Revision ID: 87e2ecb4f7ac
Revises: b4eb2fdd701d
Create Date: 2021-09-17 17:57:16.725498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e2ecb4f7ac'
down_revision = 'b4eb2fdd701d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('in_db', sa.Boolean(), nullable=True),
    sa.Column('in_db_f_data', sa.Boolean(), nullable=True),
    sa.Column('trend_f_data', sa.Boolean(), nullable=True),
    sa.Column('trend_ready', sa.Boolean(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker')
    )
    op.create_index(op.f('ix_earnings_release_date'), 'earnings_release', ['date'], unique=False)
    op.create_index(op.f('ix_earnings_release_ticker'), 'earnings_release', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_release_ticker'), table_name='earnings_release')
    op.drop_index(op.f('ix_earnings_release_date'), table_name='earnings_release')
    op.drop_table('earnings_release')
    # ### end Alembic commands ###
