"""Security Model __str__

Revision ID: 9385c7a823ef
Revises: f775266c7770
Create Date: 2021-09-14 18:05:04.898380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9385c7a823ef'
down_revision = 'f775266c7770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
