"""changed MONEY to VARCHAR

Revision ID: 978612985032
Revises: b761ed62832a
Create Date: 2021-09-14 23:13:11.299254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978612985032'
down_revision = 'b761ed62832a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
