"""Test 1

Revision ID: 99d660fb457a
Revises: 7516c00a44ef
Create Date: 2021-09-15 12:26:21.415367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d660fb457a'
down_revision = '7516c00a44ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet_annual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_bsa')
    )
    op.create_index('combo_index_bsa', 'balance_sheet_annual', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index(op.f('ix_balance_sheet_annual_date'), 'balance_sheet_annual', ['date'], unique=False)
    op.create_index(op.f('ix_balance_sheet_annual_ticker'), 'balance_sheet_annual', ['ticker'], unique=False)
    op.create_table('balance_sheet_quarterly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_bsq')
    )
    op.create_index('combo_index_bsq', 'balance_sheet_quarterly', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index(op.f('ix_balance_sheet_quarterly_date'), 'balance_sheet_quarterly', ['date'], unique=False)
    op.create_index(op.f('ix_balance_sheet_quarterly_ticker'), 'balance_sheet_quarterly', ['ticker'], unique=False)
    op.create_table('cash_flow_statement_annual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_cfa')
    )
    op.create_index(op.f('ix_cash_flow_statement_annual_date'), 'cash_flow_statement_annual', ['date'], unique=False)
    op.create_index(op.f('ix_cash_flow_statement_annual_ticker'), 'cash_flow_statement_annual', ['ticker'], unique=False)
    op.create_table('cash_flow_statement_quarterly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_cfq')
    )
    op.create_index(op.f('ix_cash_flow_statement_quarterly_date'), 'cash_flow_statement_quarterly', ['date'], unique=False)
    op.create_index(op.f('ix_cash_flow_statement_quarterly_ticker'), 'cash_flow_statement_quarterly', ['ticker'], unique=False)
    op.create_table('financial_ratios_annual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_fra')
    )
    op.create_index(op.f('ix_financial_ratios_annual_date'), 'financial_ratios_annual', ['date'], unique=False)
    op.create_index(op.f('ix_financial_ratios_annual_ticker'), 'financial_ratios_annual', ['ticker'], unique=False)
    op.create_table('financial_ratios_quarterly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_frq')
    )
    op.create_index(op.f('ix_financial_ratios_quarterly_date'), 'financial_ratios_quarterly', ['date'], unique=False)
    op.create_index(op.f('ix_financial_ratios_quarterly_ticker'), 'financial_ratios_quarterly', ['ticker'], unique=False)
    op.create_table('income_statement_annual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_isa')
    )
    op.create_index('combo_index_cfa', 'income_statement_annual', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index('combo_index_fra', 'income_statement_annual', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index('combo_index_isa', 'income_statement_annual', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index(op.f('ix_income_statement_annual_date'), 'income_statement_annual', ['date'], unique=False)
    op.create_index(op.f('ix_income_statement_annual_ticker'), 'income_statement_annual', ['ticker'], unique=False)
    op.create_table('income_statement_quarterly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', 'line_item', name='unique_entry_isq')
    )
    op.create_index('combo_index_cfq', 'income_statement_quarterly', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index('combo_index_frq', 'income_statement_quarterly', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index('combo_index_isq', 'income_statement_quarterly', ['date', 'ticker', 'line_item'], unique=False)
    op.create_index(op.f('ix_income_statement_quarterly_date'), 'income_statement_quarterly', ['date'], unique=False)
    op.create_index(op.f('ix_income_statement_quarterly_ticker'), 'income_statement_quarterly', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_statement_quarterly_ticker'), table_name='income_statement_quarterly')
    op.drop_index(op.f('ix_income_statement_quarterly_date'), table_name='income_statement_quarterly')
    op.drop_index('combo_index_isq', table_name='income_statement_quarterly')
    op.drop_index('combo_index_frq', table_name='income_statement_quarterly')
    op.drop_index('combo_index_cfq', table_name='income_statement_quarterly')
    op.drop_table('income_statement_quarterly')
    op.drop_index(op.f('ix_income_statement_annual_ticker'), table_name='income_statement_annual')
    op.drop_index(op.f('ix_income_statement_annual_date'), table_name='income_statement_annual')
    op.drop_index('combo_index_isa', table_name='income_statement_annual')
    op.drop_index('combo_index_fra', table_name='income_statement_annual')
    op.drop_index('combo_index_cfa', table_name='income_statement_annual')
    op.drop_table('income_statement_annual')
    op.drop_index(op.f('ix_financial_ratios_quarterly_ticker'), table_name='financial_ratios_quarterly')
    op.drop_index(op.f('ix_financial_ratios_quarterly_date'), table_name='financial_ratios_quarterly')
    op.drop_table('financial_ratios_quarterly')
    op.drop_index(op.f('ix_financial_ratios_annual_ticker'), table_name='financial_ratios_annual')
    op.drop_index(op.f('ix_financial_ratios_annual_date'), table_name='financial_ratios_annual')
    op.drop_table('financial_ratios_annual')
    op.drop_index(op.f('ix_cash_flow_statement_quarterly_ticker'), table_name='cash_flow_statement_quarterly')
    op.drop_index(op.f('ix_cash_flow_statement_quarterly_date'), table_name='cash_flow_statement_quarterly')
    op.drop_table('cash_flow_statement_quarterly')
    op.drop_index(op.f('ix_cash_flow_statement_annual_ticker'), table_name='cash_flow_statement_annual')
    op.drop_index(op.f('ix_cash_flow_statement_annual_date'), table_name='cash_flow_statement_annual')
    op.drop_table('cash_flow_statement_annual')
    op.drop_index(op.f('ix_balance_sheet_quarterly_ticker'), table_name='balance_sheet_quarterly')
    op.drop_index(op.f('ix_balance_sheet_quarterly_date'), table_name='balance_sheet_quarterly')
    op.drop_index('combo_index_bsq', table_name='balance_sheet_quarterly')
    op.drop_table('balance_sheet_quarterly')
    op.drop_index(op.f('ix_balance_sheet_annual_ticker'), table_name='balance_sheet_annual')
    op.drop_index(op.f('ix_balance_sheet_annual_date'), table_name='balance_sheet_annual')
    op.drop_index('combo_index_bsa', table_name='balance_sheet_annual')
    op.drop_table('balance_sheet_annual')
    # ### end Alembic commands ###
