"""Adding statements model

Revision ID: 9c85e9310439
Revises: e5e370ec34b5
Create Date: 2021-09-15 22:47:50.211351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c85e9310439'
down_revision = 'e5e370ec34b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements_table_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('added', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements_table_log')
    # ### end Alembic commands ###
