"""Security Model __str__

Revision ID: a2c321cd8872
Revises: ebea94d2c8fe
Create Date: 2021-09-14 12:14:46.026961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c321cd8872'
down_revision = 'ebea94d2c8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
