"""Changed Securities table

Revision ID: a91b00d7096a
Revises: b6d534c2e3b9
Create Date: 2021-09-13 22:25:33.263518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91b00d7096a'
down_revision = 'b6d534c2e3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
