"""Test 1

Revision ID: a9477e8ae5f4
Revises: 0ed4bbf17aae
Create Date: 2021-09-15 12:15:57.017749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9477e8ae5f4'
down_revision = '0ed4bbf17aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
