"""added Earnings-release-table

Revision ID: b4eb2fdd701d
Revises: 5d81f0e68129
Create Date: 2021-09-17 17:53:12.823788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eb2fdd701d'
down_revision = '5d81f0e68129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
