"""adding tables final

Revision ID: b612f1bd58c0
Revises: 2b30813e7f17
Create Date: 2021-09-14 19:38:04.254025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b612f1bd58c0'
down_revision = '2b30813e7f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('combo_index_bsa', 'balance_sheet_annual', ['date', 'ticker', 'line_item'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('combo_index_bsa', table_name='balance_sheet_annual')
    # ### end Alembic commands ###
