"""Changed Securities table

Revision ID: b6d534c2e3b9
Revises: 35a41641693e
Create Date: 2021-09-13 22:22:02.913301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d534c2e3b9'
down_revision = '35a41641693e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
