"""changed MONEY to VARCHAR

Revision ID: b761ed62832a
Revises: 6a477fe74fd4
Create Date: 2021-09-14 23:12:02.627675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b761ed62832a'
down_revision = '6a477fe74fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
