"""Changed Securities table

Revision ID: bd73aba1cef1
Revises: a91b00d7096a
Create Date: 2021-09-13 22:27:53.498773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd73aba1cef1'
down_revision = 'a91b00d7096a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
