"""changed MONEY to VARCHAR

Revision ID: c4b1b2a4fbfc
Revises: b612f1bd58c0
Create Date: 2021-09-14 23:07:41.181685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b1b2a4fbfc'
down_revision = 'b612f1bd58c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
