"""Security Model __str__

Revision ID: cd84df7624e6
Revises: 2dfae025dafb
Create Date: 2021-09-14 11:33:34.005390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd84df7624e6'
down_revision = '2dfae025dafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
