"""added release_date

Revision ID: df0cad7137c5
Revises: 8e2a5b4918f0
Create Date: 2021-09-22 19:29:36.366217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0cad7137c5'
down_revision = '8e2a5b4918f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_release', sa.Column('release_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_earnings_release_release_date'), 'earnings_release', ['release_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_release_release_date'), table_name='earnings_release')
    op.drop_column('earnings_release', 'release_date')
    # ### end Alembic commands ###
