"""Changed Security Model

Revision ID: eb20970a22c5
Revises: 2e45fe31a2d2
Create Date: 2021-09-14 00:50:25.272163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb20970a22c5'
down_revision = '2e45fe31a2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
