"""Security Model __str__

Revision ID: ebea94d2c8fe
Revises: cd84df7624e6
Create Date: 2021-09-14 12:14:40.010787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebea94d2c8fe'
down_revision = 'cd84df7624e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities_table_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('added', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities_table_log')
    # ### end Alembic commands ###
