"""Changed amount to FLOAT

Revision ID: ecbf512bf44d
Revises: 199786735512
Create Date: 2021-09-15 12:03:14.981363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbf512bf44d'
down_revision = '199786735512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
